"""empty message

Revision ID: 07c58cacfb80
Revises: 85ab6eca4ca8
Create Date: 2026-01-29 05:17:56.672180

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '07c58cacfb80'
down_revision = '85ab6eca4ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
