"""closed_reason

Revision ID: 37ca102bc0d3
Revises: 622472efb9a2
Create Date: 2025-11-21 10:33:29.888818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ca102bc0d3'
down_revision = '622472efb9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('closed_reason', sa.String(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('ix_tickets_status'))
        batch_op.drop_column('time_resolved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_resolved', sa.DATETIME(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tickets_status'), ['status'], unique=False)
        batch_op.drop_column('closed_reason')
        batch_op.drop_column('closed_at')

    # ### end Alembic commands ###
