"""initial setup

Revision ID: 85ab6eca4ca8
Revises:
Create Date: 2025-12-07 18:08:22.132648

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "85ab6eca4ca8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_name", sa.String(length=100), nullable=False),
        sa.Column("table", sa.String(length=50), nullable=False),
        sa.Column("physics_course", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("closed_reason", sa.String(length=20), nullable=True),
        sa.Column("number_of_students", sa.Integer(), nullable=True),
        sa.Column("wa_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["wa_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tickets_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tickets_wa_id"), ["wa_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tickets_wa_id"))
        batch_op.drop_index(batch_op.f("ix_tickets_created_at"))

    op.drop_table("tickets")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_index(batch_op.f("ix_users_created_at"))

    op.drop_table("users")
    # ### end Alembic commands ###
