"""skipped added

Revision ID: cc45944c4dda
Revises: 07c58cacfb80
Create Date: 2026-03-04 15:06:47.682269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc45944c4dda'
down_revision = '07c58cacfb80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skipped',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wa_id', sa.Integer(), nullable=False),
    sa.Column('tkt_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tkt_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wa_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skipped', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skipped_tkt_id'), ['tkt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skipped_wa_id'), ['wa_id'], unique=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['wa_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['wa_id'], ['id'])

    with op.batch_alter_table('skipped', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skipped_wa_id'))
        batch_op.drop_index(batch_op.f('ix_skipped_tkt_id'))

    op.drop_table('skipped')
    # ### end Alembic commands ###
