"""add tables

Revision ID: eb4995668263
Revises: 839e34efcba7
Create Date: 2025-11-09 21:33:46.142160

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb4995668263"
down_revision = "839e34efcba7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_tickets_time_created"))
        batch_op.create_index(
            batch_op.f("ix_tickets_created_at"), ["created_at"], unique=False
        )
        batch_op.drop_column("time_created")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("time_created", sa.DATETIME(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_tickets_created_at"))
        batch_op.create_index(
            batch_op.f("ix_tickets_time_created"), ["time_created"], unique=False
        )
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
